// examples/svelte-sveltekit/src/routes/+page.svelte
<script lang="ts">
  import { locales, t } from "yapyak";
  import { locale } from "@yapyak/svelte";
  import { switchLocale } from "./locale.remote";

  const now = new Date();
</script>

<main style="font-family: system-ui; padding: 2rem; max-width: 720px;">
  <h1>{t("Hello there")}</h1>
  <p>{t("This is the {name} example.", { name: "yapyak" })}</p>

  <h2>{t("Plurals")}</h2>
  <p>
    {t("You have {count, plural, one {# message} other {# messages}}", {
      count: 3,
    })}
  </p>
  <p>
    {t("You have {count, plural, one {# message} other {# messages}}", {
      count: 1,
    })}
  </p>

  <h2>{t("Numbers")}</h2>
  <p>{t("Total: {amount, number, percent}", { amount: 0.42 })}</p>
  <p>{t("Price: {amount, number, currency EUR}", { amount: 99.5 })}</p>
  <p>{t("Count: {amount, number, integer}", { amount: 42.7 })}</p>

  <h2>{t("Dates and times")}</h2>
  <p>{t("Updated: {when, date, long}", { when: now })}</p>
  <p>{t("Updated: {when, date, short}", { when: now })}</p>
  <p>{t("At: {when, time, short}", { when: now })}</p>

  <h2>{t("Select")}</h2>
  <p>
    {t("{role, select, admin {Administrator} editor {Editor} other {Viewer}}", {
      role: "editor",
    })}
  </p>

  <h2>{t("Switch language")}</h2>

  <p>{t("From the client")}</p>
  <div style="display: flex; gap: 0.5rem;">
    {#each locales as value (value)}
      <button
        type="button"
        disabled={value === locale.current}
        onclick={() => (locale.current = value)}
      >
        {value === "sv" ? t("Swedish") : t("English")}
      </button>
    {/each}
  </div>

  <p>{t("From the server")}</p>
  <form {...switchLocale} style="display: flex; gap: 0.5rem;">
    {#each locales as value (value)}
      <button name="locale" {value} disabled={value === locale.current}>
        {value === "sv" ? t("Swedish") : t("English")}
      </button>
    {/each}
  </form>
</main>

// examples/react-tanstack-start-cookie/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router';
import { createServerFn, useServerFn } from '@tanstack/react-start';
import { useLocale } from '@yapyak/react';
import { locales, setLocale, t } from 'yapyak';

const date = new Date('2024-01-01T08:30:00Z');

const switchLocale = createServerFn({ method: 'POST' })
  .inputValidator((locale: string) => locale)
  .handler(({ data }) => {
    setLocale(data);
  });

export const Route = createFileRoute('/')({
  component: Component,
});

function Component() {
  const [locale, setLocale] = useLocale();
  const submit = useServerFn(switchLocale);
  return (
    <main
      style={{ fontFamily: 'system-ui', maxWidth: '720px', padding: '2rem' }}
    >
      <h1>{t('Hello there')}</h1>
      <p>{t('This is the {name} example.', { name: 'yapyak' })}</p>

      <h2>{t('Plurals')}</h2>
      <p>
        {t('You have {count, plural, one {# message} other {# messages}}', {
          count: 3,
        })}
      </p>
      <p>
        {t('You have {count, plural, one {# message} other {# messages}}', {
          count: 1,
        })}
      </p>

      <h2>{t('Numbers')}</h2>
      <p>{t('Total: {amount, number, percent}', { amount: 0.42 })}</p>
      <p>{t('Price: {amount, number, currency EUR}', { amount: 99.5 })}</p>
      <p>{t('Count: {amount, number, integer}', { amount: 42.7 })}</p>

      <h2>{t('Dates and times')}</h2>
      <p>{t('Updated: {when, date, long}', { when: date })}</p>
      <p>{t('Updated: {when, date, short}', { when: date })}</p>
      <p>{t('At: {when, time, short}', { when: date })}</p>

      <h2>{t('Select')}</h2>
      <p>
        {t(
          '{role, select, admin {Administrator} editor {Editor} other {Viewer}}',
          { role: 'editor' },
        )}
      </p>

      <h2>{t('Switch language')}</h2>

      <p>{t('From the client')}</p>
      <div style={{ display: 'flex', gap: '0.5rem' }}>
        {locales.map((value) => (
          <button
            disabled={value === locale}
            key={value}
            onClick={() => setLocale(value)}
            type="button"
          >
            {value === 'sv' ? t('Swedish') : t('English')}
          </button>
        ))}
      </div>

      <p>{t('From the server')}</p>
      <div style={{ display: 'flex', gap: '0.5rem' }}>
        {locales.map((value) => (
          <button
            disabled={value === locale}
            key={value}
            onClick={() => submit({ data: value })}
            type="button"
          >
            {value === 'sv' ? t('Swedish') : t('English')}
          </button>
        ))}
      </div>
    </main>
  );
}
